### ISSUE TITLE
关于权限获取

### ISSUE THREAD

**Issue by LaoADe** [zhangliangming/HappyPlayer5#11]
在我的华为手机上运行时，在启动页获取储存权限，之后在主页中获取电话和短信权限，主页弹出的申请框会把启动页弹出的申请框给刷掉，导致储存权限获取不到

**Comment by zhangliangming** [comment]
` /**
     * 处理后台数据
     */
    private void doSomeThing() {
        //是否是第一次使用
        boolean isFrist = PreferencesUtil.getBooleanValue(getApplicationContext(), PreferencesConstants.isFrist_KEY, true);
        if (isFrist) {
            //第一次使用扫描本地歌曲
            final List<AudioInfo> audioInfos = new ArrayList<AudioInfo>();
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                AndPermission.with(mActivity)
                        .requestCode(110)
                        .permission(Manifest.permission.READ_EXTERNAL_STORAGE,
                                Manifest.permission.WRITE_EXTERNAL_STORAGE)
                        .callback(new PermissionListener() {
                            @Override
                            public void onSucceed(int requestCode, @NonNull List<String> grantPermissions) {
                                scanLocalMusic(audioInfos);
                            }

                            @Override
                            public void onFailed(int requestCode, @NonNull List<String> deniedPermissions) {
                                AlartTwoButtonDialog mExitAlartDialog = new AlartTwoButtonDialog(mActivity, new AlartTwoButtonDialog.TwoButtonDialogListener() {
                                    @Override
                                    public void oneButtonClick() {

                                    }

                                    @Override
                                    public void twoButtonClick() {

                                    }
                                });
                                mExitAlartDialog.showDialog(mContext.getString(R.string.need_access_read_write_external_storage),
                                        mContext.getString(R.string.cancel),
                                        mContext.getString(R.string.sure));
                            }
                        }).start();
            }else {
                scanLocalMusic(audioInfos);
            }

        } else {
            //设置延迟时间
            mDelayTime *= 3;
        }
        //初始化配置数据
        initPreferencesData();
        loadSplashMusic();
        mAnimationHandler.postDelayed(mAnimationRunnable, mDelayTime);
    }

    private void scanLocalMusic(final List<AudioInfo> audioInfos) {
        MediaUtil.scanLocalMusic(SplashActivity.this, new MediaUtil.ForeachListener() {
            @Override
            public void foreach(AudioInfo audioInfo) {
                if (audioInfo != null) {
                    audioInfos.add(audioInfo);
                }
            }

            @Override
            public boolean filter(String hash) {
                return AudioInfoDB.getAudioInfoDB(getApplicationContext()).isExists(hash);
            }
        });
        if (audioInfos.size() > 0) {
            AudioInfoDB.getAudioInfoDB(getApplicationContext()).add(audioInfos);
        }

        //设置延迟时间
        mDelayTime *= 2;
        HPApplication.getInstance().setFrist(false);
    }`


<string name="need_access_read_write_external_storage">需要访问本地读写权限</string>

**Comment by DyncKathline** [comment]
已修复，请clone一下代码
