### ISSUE TITLE
apk也太大了吧

### ISSUE THREAD

**Issue by AndMy** [zhangliangming/HappyPlayer5#12]
apk也太大了吧 37M

**Comment by zhangliangming** [comment]
@AndMy 主要是因为项目引用了ijkplayer的so文件，所以整个安装包会比较大，现在我的项目优化了，删除了部分so文件和jar文件，改为通过gradle配置文件实现。现在的apk包大概就20m左右吧。你可以到zlm分支下载，或者更新一下你本地的代码。
