### ISSUE TITLE
第一进app和网络请求都好慢啊

### ISSUE THREAD

**Issue by LyKevin** [zhangliangming/HappyPlayer5#14]
第一进app会黑屏很长时间, 然后网络请求也很慢很慢.....  进度条转至少有一分钟才显示东西.......

**Comment by DyncKathline** [comment]
很多地方加了延时，你可以[https://github.com/zhangliangming/HappyPlayer5/tree/master](下载master分支)

**Comment by DyncKathline** [comment]
很多加载数据的地方加了延时，另外你可以切换至master分支

**Comment by liguangze** [comment]
现在下载的不是master分支吗，怎么切换到master分支
