### ISSUE TITLE
你好，请问在线播放音乐可以做到提取到专辑图片等信息吗

### ISSUE THREAD

**Issue by Virgilseed** [zhangliangming/HappyPlayer5#15]

**Comment by zhangliangming** [comment]
1.如果从歌曲文件里面获取专辑图片，那么你在线播放歌曲的时候，要知道专辑图片在歌曲文件里面的位置，然后从文件流中获取图片。
2.在线歌曲，别人一般都提供一个接口，直接获取专辑图片。
