### ISSUE TITLE
是否缺少SwipeBackLayout等文件？

### ISSUE THREAD

**Issue by flswld** [zhangliangming/HappyPlayer5#16]
import com.zlm.libs.widget.SwipeBackLayout;
报错，不存在。

**Comment by zhangliangming** [comment]
这个类我已经弄成依赖包了
dependencies { compile 'com.github.zhangliangming:SwipeBackLayout:v2.0' }
具体参考：https://github.com/zhangliangming/SwipeBackLayout

**Comment by zhangliangming** [comment]
到时你在hp项目里面直接引用就可以了。
