### ISSUE TITLE
第二次登录是怎么判断的

### ISSUE THREAD

**Issue by superxsx** [zhangliangming/HappyPlayer5#17]
小白想问下：第二次登录是怎么判断的 好像没走SplashActivity这个类

**Comment by zhangliangming** [comment]
没登录这一说法，只是有判断是否是第一次使用，其中SplashActivity 类中不是有
`boolean isFrist = (boolean) PreferencesUtil.getValue(getApplicationContext(), PreferencesConstants.isFrist_KEY, true);`
还有，你可以看AndroidManifest.xml这个文件，程序入口就是SplashActivity。

**Comment by superxsx** [comment]
感谢楼主的解答 我已经明白了  
我又遇到了一个问题，在加载歌词的时候 代码如下
lyricsReader.loadLrc(newFile("/storage/emulated/0/Android/data/com.xsx.xiaoyuyingyue/cache/ACache/0e8f88e002e38a0b680e440d319f2fa4.krc"));
手机目录下  /storage/emulated/0/Android/data/com.xsx.xiaoyuyingyue/cache/ACache/0e8f88e002e38a0b680e440d319f2fa4.krc   这个歌词文件是存在的  0e8f88e002e38a0b680e440d319f2fa4是 AudioInfo的hash值
结果报
java.lang.AssertionError: java.util.zip.ZipException: incorrect header check
这个错 楼主知道什么原因吗  多谢楼主抽空看下

**Comment by zhangliangming** [comment]
@superxsx 
1.这种情况大多是文件有问题，你先确定你没有修改过该歌词文件
2.你可以尝试用酷狗软件来打开这个文件，看酷狗是否能读取，如果不能读取，就说明文件已经被损坏了。
3.我看你代码，并不像是我播放器里面的文件路径，你先确保你下载该歌词的接口是否有问题。
4.以上都不行，也麻烦你把krc歌词文件也上传一下，你这样子，我也是一头雾水

**Comment by superxsx** [comment]
@zhangliangming 
楼主 是文件损坏了  
我用的是ACache这个轻量级缓存文件 缓存写入文件的时候可能会出现损坏

**Comment by zhangliangming** [comment]
@superxsx 如果是关于文件byte[]与string之间的转换，一定要用base64来处理
