### ISSUE TITLE
如果要做精确定位 是否一定要krc格式

### ISSUE THREAD

**Issue by zhongwen1** [zhangliangming/HappyPlayer5#19]
让版权运营商提供krc格式的歌词 是吗

**Comment by zhangliangming** [comment]
@zhongwen1 网上有好多精确定位的歌词格式的如：krc，ksc，trc，qrc等等，不过我的播放器目前只支持krc，ksc和hrc(我自己定义的歌词格式)。如果你要支持trc，qrc这些歌词格式，需要你自己去拓展。
