### ISSUE TITLE
studio 环境

### ISSUE THREAD

**Issue by marren06** [zhangliangming/HappyPlayer5#2]
作者studio环境是不是3.0 预览版本？
![image](https://user-images.githubusercontent.com/17778482/30895167-f7be14ba-a37a-11e7-8032-ec4eebd90c24.png)
现在正是版本还没发布，不想影响我的正常稳定项目，所以我没有安装 preview 版本

**Comment by zhangliangming** [comment]
是的，我的是Preview版本的，目前，只能是你在电脑上面安装多一个Preview版本的studio来运行我的项目就可以了。
