### ISSUE TITLE
那hrc和krc的歌词文件如何制作

### ISSUE THREAD

**Issue by zhongwen1** [zhangliangming/HappyPlayer5#20]
是需要我们告诉唱片公司歌词制作方法，还是他们提供。

**Comment by zhangliangming** [comment]
@zhongwen1 我觉得你还是要先好好了解一下歌词这一块的知识，或者上网查一下相关的资料，先了解一些基础知识再看来我的项目，也请你认真看一下readme里面的内容。
1.关于krc歌词怎样制作，如果你有用过“酷狗”的应该都知道。
2.关于hrc歌词怎样制作，如果你有认真看readme，你应该会发现传送门有一个制作歌词的链接及相关博客。
3.关于hrc歌词，这个是我乐乐播放器自定义的歌词格式，这个格式，你不要用于商业用途，readme里我是有声明的。
4.关于唱片公司的问题，由谁来提供和制作，这些都是你与唱片公司的合同问题，如果由唱片公司提供，那你是否需要考虑他们是否有软件制作歌词或者告诉他们制作歌词流程等等。

**Comment by zhongwen1** [comment]
@zhangliangming 您的建议我会认真看
1.关于hrc歌词格式，我不会用来做商业用途。
2.只是项目开始了，我现在需要给出个音乐歌词格式给公司；公司需要知道歌词的格式好和版权商商谈。
3.我会去了解相关的歌词基础知识，然后给出个音乐格式给公司。

**Comment by zhangliangming** [comment]
@zhongwen1 嗯。就目前来看，比较方便的就是ksc歌词，网上也有一些好的制作软件，如《小灰熊卡拉ok字幕制作软件》，对于歌词制作也方便，也是精确到每个字的。

**Comment by zhongwen1** [comment]
能加个微信吗

**Comment by zhongwen1** [comment]
不过github提问也是可以的。

**Comment by zhongwen1** [comment]
特来道谢，谢谢指明方向。
1 用小灰熊软件制作了歌词，并使用了酷狗的歌词制作软件，也用你的歌词播放demo播出来了。
2 并知道了歌词制作的原理，就是记录一个歌词的播放时长。
