### ISSUE TITLE
有支持无损格式解码的代码吗?能独立出来吗?

### ISSUE THREAD

**Issue by Aima09** [zhangliangming/HappyPlayer5#21]

**Comment by zhangliangming** [comment]
@linford1012 只写了一个音频解析库，只是做了一些音频的基本信息的解析，没有做音频解码的。目前播放歌曲使用的是ijkplayer，音频的解码都交给它来做了。有兴趣的，你可以到ijkplayer的官网看看，地址如下：[https://github.com/Bilibili/ijkplayer](https://github.com/Bilibili/ijkplayer)。又或者你真想做解码的话，网上有一个是使用纯java来解码的java swing项目，你可以到该项目上面看看，项目地址：[https://github.com/tulskiy/musique](https://github.com/tulskiy/musique)，它这个项目，也是支持损格式的解码的，不过，我之前尝试过把它转成android的项目，不过无损格式的歌曲解码时，有点卡。你也可以到这个android项目看看，项目地址：[https://github.com/zhangliangming/Android_AudioPlayer](https://github.com/zhangliangming/Android_AudioPlayer)
