### ISSUE TITLE
你把apk也提交上来了 文件太大导致源码也下载不下来

### ISSUE THREAD

**Issue by zhengzaihong** [zhangliangming/HappyPlayer5#22]
你把apk也提交上来了 文件太大导致源码也下载不下来

**Comment by zhangliangming** [comment]
@zhengzaihong 我之前试过使用github的客户端，是可以下载的。或者你考虑一下，直接用浏览器下载项目，然后再导入as，之前为了方便，就将apk包也放上去了。
