### ISSUE TITLE
作者有没有研究过如何进一步缩小ijkplayer的.so库大小

### ISSUE THREAD

**Issue by rRemix** [zhangliangming/HappyPlayer5#23]
能够支持常用的音频格式(包括无损)，同时屏蔽掉所有视频格式,，让so文件最小

**Comment by zhangliangming** [comment]
@rRemix 你可以到ijkplayer官网看看，有没有人做了这个操作，我也想弄小一点。还有后面，我还要把mv功能添加上去的，所以不能屏蔽掉所有视频格式。
