### ISSUE TITLE
作者有没有想过加入 Equalizer(均衡器) 的一些播放效果么？

### ISSUE THREAD

**Issue by 7280423** [zhangliangming/HappyPlayer5#24]
对ijkplayer 尚在调研阶段，想法和你一样，将来要预留mv播放，所以想用ijkplayer 做一款音乐播放器，但是现在发现不知道怎么用这个来加入均衡器的效果（ios 版本）

**Comment by zhangliangming** [comment]
@7280423 我都没研究过均衡器[哭笑]
