### ISSUE TITLE
android 8.0 以上 recent 键 bug

### ISSUE THREAD

**Issue by heyleon** [zhangliangming/HappyPlayer5#29]
点击多任务按键 出现bug
 
1,进入二级activity 按多任务键 正常
2,从多任务回到app 按 back 键 再按多任务键 显示的是已经finish的activity 并不是当前activity 

请问是什么原因

**Comment by zhangliangming** [comment]
@heyleon 二级界面除了歌词界面，其它一般都是Fragment。应该是不会有问题的。如果可以，麻烦提供一下，截图

**Comment by heyleon** [comment]
![screenshot_20181027-085011](https://user-images.githubusercontent.com/19371845/47597816-73d62980-d9c5-11e8-9b8e-ca2c8f86c86f.jpg)
![screenshot_20181027-085020](https://user-images.githubusercontent.com/19371845/47597817-759fed00-d9c5-11e8-9452-86d86b5853d2.jpg)
![screenshot_20181027-085027](https://user-images.githubusercontent.com/19371845/47597818-78024700-d9c5-11e8-9a9a-a7fee16f24a6.jpg)
感谢回复,以上是演示过程

**Comment by zhangliangming** [comment]
@heyleon 我用小米8.0的机子，试了一下，无问题。。。。可能是手机的问题
