### ISSUE TITLE
可以缓存音乐吗

### ISSUE THREAD

**Issue by dengzhao7053** [zhangliangming/HappyPlayer5#3]
如题，听过的音乐可以缓存下来吗

**Comment by zhangliangming** [comment]
我这边实现的是边听边下载。试听过的歌曲都会被下载到一个sd卡文件夹（haplayer/cache/audio）里面，下次再听时，直接从手机sd卡里面加载

**Comment by sing1** [comment]
有的歌曲好像下载不完整，听一半也跳转下一首了，在本地SD卡中找到音乐用系统播放器也是听一半直接结束了
