### ISSUE TITLE
开启桌面歌词后，整个手机无法back。

### ISSUE THREAD

**Issue by xudongjian233** [zhangliangming/HappyPlayer5#30]
开启桌面歌词后，无论锁定或不锁定桌面歌词，其他app都会无法back
机型：魅族15，安卓版本：7.1.1
机型：小米8se，安卓版本：8.1.0

**Comment by zhangliangming** [comment]
@xudongjian233 这个问题，在happy_player6的分支上面已经修复了。在5这个分支上面，你可以找到FloatService这个类，

 mLayout.flags = WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE | WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL;

 mLayout.flags = WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE | WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE;

对，就是添加多一个WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE 。这样子，桌面歌词出来后，还是可以点击返回

**Comment by zhangliangming** [comment]
@xudongjian233 如有需要可更新happy_player6的分支
