### ISSUE TITLE
ijkplayer无法播放wav格式的歌曲

### ISSUE THREAD

**Issue by magic0908** [zhangliangming/HappyPlayer5#32]
SD卡有一首歌曲是wav格式的，但是在ijkplayer却无法播放

**Comment by zhangliangming** [comment]
@magic0908 这个和ijkplayer是没有关系的，只要是我在播放歌曲时，没有判断是不是本地扫描的歌曲。全部当作是网络歌曲来播放了，导致找不到文件路径。最新代码已经修复了。

**Comment by magic0908** [comment]
我的项目中也是集成了ijkplayer，但是无论播放本地的wav还是网络的都播不了，楼主知道可能是什么原因不

**Comment by zhangliangming** [comment]
@magic0908 ijkplayer官网，dependencies 进来的都是不支持无损格式的，如flac、ape、wav等等。如果想要支持无损格式，需要自己重新编译。给你一个地址参考：https://www.jianshu.com/p/9743a68c2939 ，如果不想重新编译，网上应该有好多已经编译好支持多格式的so文件，直接使用就行
