### ISSUE TITLE
happyplayer6 分支bug

### ISSUE THREAD

**Issue by tianshaokai** [zhangliangming/HappyPlayer5#33]
![image](https://user-images.githubusercontent.com/6706496/54573939-45ff8900-4a29-11e9-95ac-e413f48547b3.png)

1. 首页首次进入很长时间一直停留在闪屏页面
2. 杀掉app后从新进入后就可以了

**Comment by tianshaokai** [comment]
可否加作者一个联系方式交流一下安卓开发啊

**Comment by tianshaokai** [comment]
gradle 目录文件希望改成这个，原来的无法编译成功
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

**Comment by tianshaokai** [comment]
当前分支缺少这个类，SubtitleInfoDao

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/54576177-0d17e200-4a32-11e9-84aa-cb3982da3b89.png)
我是从master 分支checkout happyplayer6分支的，这两个类总是有改动，希望作者看一下那块有问题

**Comment by zhangliangming** [comment]
@tianshaokai 
1.启动页停留久的问题，可能是我前几天优化了权限的问题导致的。昨晚我已经修复这个问题了，你更新一下代码。
2.DAO相关的类总是改动，主要是greenDAO在build的时候，会自动生成DAO的文件，这个你看greenDAO的框架和相关资料就行。
3.gradle你修改为你自己本地的就可以，这个没限制的。

**Comment by zhangliangming** [comment]
@tianshaokai 对于你贴图的代码，这个就真是搞不明白了。我应该没有在主线程发网络请求的才对，不知你是怎样出现这个问题的。

**Comment by tianshaokai** [comment]
greendao 我以前用过2.x 的版本发现dao 和 session 不会在build 的时候变化啊，2.x 和 3.x 实现方式不一样吗，对了net.zetetic:android-database-sqlcipher 这个库是不是没有使用啊

**Comment by zhangliangming** [comment]
@tianshaokai 你直接删掉dao，再build一下，就可以知道了。sqlcipher类有用到的，数据库加密用的，具体查一下greenDAO的框架的相关资料。

你更新代码之后，还有没有问题？

**Comment by tianshaokai** [comment]
还有一个问题就是没有看到sqlcipher在哪使用的

**Comment by zhangliangming** [comment]
@tianshaokai 如果数据库加密，那greendao里面有调用到sqlcipher的类。

**Comment by tianshaokai** [comment]
@zhangliangming 锁屏歌词开关 关闭后重启app 后依然开启，
希望作者可以加一下sqlcipher的使用，看看它是如何使用的、

**Comment by tianshaokai** [comment]
我在下载歌曲的时候，截图的android.os.NetworkOnMainThreadException 异常就会抛出来了

**Comment by zhangliangming** [comment]
@tianshaokai 你说的下载歌曲的代码真的是有问题。最新代码已经修复了。
其实关于sqlcipher的用法，目前没有时间去深入研究。。。。。
