### ISSUE TITLE
桌面浮窗

### ISSUE THREAD

**Issue by Born-alone** [zhangliangming/HappyPlayer5#34]
现在我的桌面浮窗没有那个大 怎么设置它可以滑动到屏幕任意位置呢

**Comment by zhangliangming** [comment]
@Born-alone FloatService 中的以下代码，可设置桌面歌词窗口的位置和大小，具体你看代码或者看一下WindowManager的api。

` mLayout.y = mConfigInfo.getDesktopLrcY();`

**Comment by Born-alone** [comment]
mLayout.y = mConfigInfo.getDesktopLrcY();
我把这行代码注释了 他还是只能在竖直方向滑动呐

**Comment by zhangliangming** [comment]
@Born-alone 老铁，你这问题与你问的有点不一致。目前桌面歌词的面板，我限制了只能上下移动，不支持左右移动。需要你自己到FloatLinearLayout这个类里面做拓展，支持左右移动。然后设置mLayout.y，mLayout.x即可

**Comment by Born-alone** [comment]
好的 了解
