### ISSUE TITLE
建议在6.0系统手机或者模拟器上测试一下，兼容高版本

### ISSUE THREAD

**Issue by liuxuebing2010** [zhangliangming/HappyPlayer5#4]
在Android6.0上面初始化会崩，点击扫描音乐也会崩

**Comment by totond** [comment]
这应该是权限问题，我在手机上手动把存储权限打开就行了，建议作者加入动态权限请求。

**Comment by zhangliangming** [comment]
@liuxuebing2010 @totond 有2个方案
1.添加动态权限请求
2.修改build.gradle文件中的targetSdkVersion，设置在22以下，就正常了。

后面，我尝试一下添加一个动态权限请求

**Comment by zhangliangming** [comment]
@liuxuebing2010 @totond 关于6.0系统的动态权限问题，我已简单修复。
