### ISSUE TITLE
RotateLinearLayout旋转角度在0.x时LrcActivity页面layout_lrc_playbar布局会闪烁

### ISSUE THREAD

**Issue by DyncKathline** [zhangliangming/HappyPlayer5#6]
如题，请问如何解决

**Comment by zhangliangming** [comment]
@DyncKathline 可能是动画问题，你试一下修改动画
mAnimator.setInterpolator(new LinearInterpolator());
你也可以尝试其它的动画试试。

**Comment by DyncKathline** [comment]
mAnimator.setInterpolator(new LinearInterpolator());注释掉这句也没用，我现在做法是在更新动画的时候判断它的旋转角度小于0.2就直接设置成0这样就不会闪烁了，可这样做没找到根本原因。

**Comment by zhangliangming** [comment]
之前一直都是用手机做的测试，在我测试机上没发现这个问题，在模拟器上面运行，确实有这个问题。感觉你这样子，那动画会不会不流畅？ @DyncKathline

**Comment by DyncKathline** [comment]
不会的，昨天电脑不在
![image](https://user-images.githubusercontent.com/16282974/34700656-271c0cd0-f51f-11e7-93db-f852bea6f6f8.png)

**Comment by zhangliangming** [comment]
@DyncKathline 我网上查了一下，好像有些人也有这种情况，不过未解决。对了，你是用真机测试的，还是用模拟器？

**Comment by DyncKathline** [comment]
真机

**Comment by zhangliangming** [comment]
@DyncKathline 方便说一下机型和系统版本吗？

**Comment by DyncKathline** [comment]
vivox7 Android7.1

**Comment by zhangliangming** [comment]
@DyncKathline 好的同，非常感谢。

**Comment by zhangliangming** [comment]
@DyncKathline 你尝试一下把ValueAnimator.ofFloat修改为ValueAnimator.ofInt。这样子看一下闪烁是否还在，我把它修改之后，在模拟器上面运行，已经没有闪烁的问题了。你可以修改后，在真机上面试一下。

**Comment by DyncKathline** [comment]
好的明天试试，谢谢

**Comment by DyncKathline** [comment]
好了，但是还有一个小缺点，就是左右划来划去，在MotionEvent.ACTION_MOVE:这里设置setRotation(degree);还是会有小数值，会有闪烁

**Comment by zhangliangming** [comment]
之前左右操作时，一直都存在闪烁的问题？

**Comment by DyncKathline** [comment]
是的，感觉是不能小数吧，更新了你那个关闭动画的，因为在MotionEvent.ACTION_MOVE:那里没有

**Comment by zhangliangming** [comment]
感觉是整数的话，旋转不流畅。这样吧，你到我github上面更新一下RotateLinearLayout这个类的代码（把你之前的这个类文件保存好），更新之后，看看还有没这个问题。

**Comment by DyncKathline** [comment]
![image](https://user-images.githubusercontent.com/16282974/34925276-4dd49f2c-f9e3-11e7-9207-9acc7e788d8a.png)
是的，我刚试了下，换成整数的话，左右滑动会不流畅

**Comment by zhangliangming** [comment]
RotateLinearLayout这个类，你更新一下我最新代码。没理由的，想不通…😣

**Comment by DyncKathline** [comment]
我另外再clone了你的代码运行，左右移动，在角度0.x几的时候会闪烁，松开reset动画没问题了

**Comment by zhangliangming** [comment]
🙀😿，容我想想先。非常感谢你😁

**Comment by DyncKathline** [comment]
可以加个QQ吗，方便联系问题？

**Comment by zhangliangming** [comment]
@DyncKathline 316257874。

**Comment by zhangliangming** [comment]
@DyncKathline 关闭硬件加速。![](https://i.imgur.com/7X52A2d.png)
