### ISSUE TITLE
转换去apk出现错误

### ISSUE THREAD

**Issue by JohnW4086** [zhangliangming/HappyPlayer5#9]
![1-1](https://user-images.githubusercontent.com/35675043/35203695-77aea3fc-ff64-11e7-884c-a382605eb917.png)

Android studio 3.0.1
请教导如何解决这问题，谢谢
我根本不会Programming技巧
请列出解决方法，再次谢谢

**Comment by DyncKathline** [comment]
Bugly.init(getApplicationContext(), Constant.BUGLY_APPID, false);
这句可以注释掉

**Comment by JohnW4086** [comment]
我华语不是很好。。注释是什么意思？可以列出明确的方法吗？谢谢

**Comment by DyncKathline** [comment]
//Bugly.init(getApplicationContext(), Constant.BUGLY_APPID, false);
这样做

**Comment by JohnW4086** [comment]
就是说前面加那两个／／然后跟着打你给的一模一样就可以了是吗？

**Comment by DyncKathline** [comment]
是的，我最新代码已经注释掉了，你可以再clone一下

**Comment by JohnW4086** [comment]
再次从github下载是吗？

**Comment by DyncKathline** [comment]
是的

**Comment by DyncKathline** [comment]
你也可以看这里
https://github.com/zhangliangming/HappyPlayer5/commit/73c15893a315c9b55a64ffbe6c3db24246c8d3a4

**Comment by JohnW4086** [comment]
![screenshot_2018-01-22-14-41-01-85](https://user-images.githubusercontent.com/35675043/35208272-73d48fda-ff82-11e7-9ae5-a1580d9fa875.png)
谢谢。。解决了，不过夜间模式和换肤按了就自动退出，排行的歌曲图案无法显示，不过歌曲能下载
![screenshot_2018-01-22-14-41-07-41](https://user-images.githubusercontent.com/35675043/35208267-6b09159c-ff82-11e7-978a-cdddbb4c12f0.png)

**Comment by DyncKathline** [comment]
嗯嗯，功能正在实现中
